package com.antipattern.service;

/**
 * Created by rajith on 4/17/17.
 */
public class LongMethodService {

    /**
     * this is m1
     */
    public void m1() {
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
    }

    public void m2() {
        System.out.println("b");
        System.out.println("b");
        System.out.println("b");
        System.out.println("b");
        System.out.println("b");
        System.out.println("b");
        System.out.println("b");
        System.out.println("b");
        System.out.println("b");
        System.out.println("b");
        System.out.println("b");
        System.out.println("b");
        System.out.println("b");
        System.out.println("b");
        System.out.println("b");
        System.out.println("b");
        System.out.println("b");
        System.out.println("b");
        System.out.println("b");
        System.out.println("b");
        System.out.println("b");
        System.out.println("b");
        System.out.println("b");
        System.out.println("b");
        System.out.println("b");
        System.out.println("b");
        System.out.println("b");
        System.out.println("b");
        System.out.println("b");
        System.out.println("b");
        System.out.println("b");
        System.out.println("b");
        System.out.println("b");
        System.out.println("b");
        System.out.println("b");
        System.out.println("b");
        System.out.println("b");
        System.out.println("b");
        System.out.println("b");
        System.out.println("b");
        System.out.println("b");
        System.out.println("b");
        System.out.println("b");
        System.out.println("b");
    }

    public void m3(int a, String b, int c, long d){
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
        System.out.println("a");
    }


}
